export const GET_ALL_FEDERATIONS = "GET_ALL_FEDERATIONS";
export const GET_ALL_FEDERATIONS_SUCCESS = "GET_ALL_FEDERATIONS_SUCCESS";
export const GET_ALL_FEDERATIONS_FAILURE = "GET_ALL_FEDERATIONS_FAILURE";
export const GET_SINGLE_FEDERATION = "GET_SINGLE_FEDERATION";
export const GET_SINGLE_FEDERATION_SUCCESS = "GET_SINGLE_FEDERATION_SUCCESS";
export const GET_SINGLE_FEDERATION_FAILURE = "GET_SINGLE_FEDERATION_FAILURE";
export const REGISTER_FEDERATION = "REGISTER_FEDERATION";
export const REGISTER_FEDERATION_SUCCESS = "REGISTER_FEDERATION_SUCCESS";
export const REGISTER_FEDERATION_FAILURE = "REGISTER_FEDERATION_FAILURE";

export const GET_ALL_UNIONS = "GET_ALL_UNIONS";
export const GET_ALL_UNIONS_SUCCESS = "GET_ALL_UNIONS_SUCCESS";
export const GET_ALL_UNIONS_FAILURE = "GET_ALL_UNIONS_FAILURE";
export const GET_UNION_BY_FEDERATION = "GET_UNION_BY_FEDERATION";
export const GET_UNION_BY_FEDERATION_SUCCESS =
  "GET_UNION_BY_FEDERATION_SUCCESS";
export const GET_UNION_BY_FEDERATION_FAILURE = "GET_ALL_FEDERATION_FAILURE";
export const GET_SINGLE_UNION = "GET_SINGLE_UNION";
export const GET_SINGLE_UNION_SUCCESS = "GET_SINGLE_UNION_SUCCESS";
export const GET_SINGLE_UNION_FAILURE = "GET_SINGLE_UNION_FAILURE";
export const GET_ARTISTS_IN_UNION = "GET_ARTISTS_IN_UNION";
export const GET_ARTISTS_IN_UNION_SUCCESS = "GET_ARTISTS_IN_UNION_SUCCESS";
export const GET_ARTISTS_IN_UNION_FAILURE = "GET_ARTISTS_IN_UNION_FAILURE";
