export const GET_ALL_FEDERATIONS = "GET_ALL_FEDERATIONS";
export const GET_ALL_FEDERATIONS_SUCCESS = "GET_ALL_FEDERATIONS_SUCCESS";
export const GET_ALL_FEDERATIONS_FAILURE = "GET_ALL_FEDERATIONS_FAILURE";

export const REGISTER_FEDERATION = "REGISTER_FEDERATION";
export const REGISTER_FEDERATION_SUCCESS = "REGISTER_FEDERATION_SUCCESS";
export const REGISTER_FEDERATION_FAILURE = "REGISTER_FEDERATION_FAILURE";
