const base_uri=`https://rwanda-art-api.herokuapp.com/api/ViewUser`
    
  const token='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vcndhbmRhLWFydC1hcGkuaGVyb2t1YXBwLmNvbS9hcGkvbG9naW4iLCJpYXQiOjE2NjA5MTA2ODQsImV4cCI6MTY2MDkxNDI4NCwibmJmIjoxNjYwOTEwNjg0LCJqdGkiOiJmcEJ3OWNoYW9qaG9DSVBCIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJ1c2VyIjp7ImlkIjoxLCJmZWRlcmF0aW9uX25hbWUiOiJSd2FuZGFBcnRDb3VuY2lsIiwicGhvbmVfbnVtYmVyIjoiMDc4NTQxOTc3MyIsImltYWdlIjoiam8uanBnIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ0aW5udW1iZXIiOjExMTExLCJmaWxlIjoia2tray5qcGciLCJudW1iZXJfb2ZfbWVtYmVycyI6MTIxLCJjYXRlZ29yeV9pZCI6bnVsbCwic3RhdHVzIjoiUGVuZGluZyJ9fQ.J1cfjYXrri_l2YQXhqp9pyTcqfSpDkbysdmwVA8iJGc'
  localStorage.setItem('token','Bearer' +token) 
     
  const tok=localStorage.getItem('token');

export function getTocken(){
    return tok;
}