const base_uri=`https://rwanda-art-api.herokuapp.com/api/ViewUser`
    
  const token='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vcndhbmRhLWFydC1hcGkuaGVyb2t1YXBwLmNvbS9hcGkvbG9naW4iLCJpYXQiOjE2NjExNjc4NjQsImV4cCI6MTY2MTE3MTQ2NCwibmJmIjoxNjYxMTY3ODY0LCJqdGkiOiJZTTlwOUlsTlVJaTVWSUlOIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJ1c2VyIjp7ImlkIjoxLCJmZWRlcmF0aW9uX25hbWUiOiJSd2FuZGFBcnRDb3VuY2lsIiwicGhvbmVfbnVtYmVyIjoiMDc4NTQxOTc3MyIsImltYWdlIjoiam8uanBnIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJ0aW5udW1iZXIiOjExMTExLCJmaWxlIjoia2tray5qcGciLCJudW1iZXJfb2ZfbWVtYmVycyI6MTIxLCJjYXRlZ29yeV9pZCI6bnVsbCwic3RhdHVzIjoiUGVuZGluZyJ9fQ.S0joYTyIHSRNMYu_V7klxgBacC57oGMam_zjIz1-EtM'
  localStorage.setItem('token','Bearer ' +token) 
     
  const tok=localStorage.getItem('token');

export  function getTocken(){
    return  tok;
}